# Generated by Django 4.1.2 on 2022-10-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydetail',
            old_name='Bio',
            new_name='bio',
        ),
    ]
